### ISSUE TITLE
use transferFile method in iOS transfer realm file to watchos show me error.

### ISSUE THREAD

**Issue by Softminilab** [hsylife/SampleRealmOnWatchOS3#1]
show me error, "default.realm.management': make_dir() failed: Operation not permitted"

**Comment by hsylife** [comment]
@karepbq,
Thanks for creating the issue.
Does the error occur while running on a device, not on a simulator?

**Comment by Softminilab** [comment]
yes, when I run project, use this method, I received an error.

**Comment by hsylife** [comment]
@karepbq, thanks.
We should carefully limit the range of error.
We have confirmed that the error never occur on a simulator.
Next, I want to reproduce the error which you mentioned. Unfortunately, my apple watch ran out of power. Give me time until the watch is available.

**Comment by Softminilab** [comment]
> in iOS code
```
      Realm.Configuration.defaultConfiguration = configuration
        
        if let url =  Realm.Configuration.defaultConfiguration.fileURL {
            if #available(iOS 9.0, *) {
                WCSession.defaultSession().transferFile(url, metadata: nil)
            } else {
                // Fallback on earlier versions
            }
        }
```

>  in watchos code
```
func session(session: WCSession, didReceiveFile file: WCSessionFile) {
        var config = Realm.Configuration()
        config.fileURL = file.fileURL
        Realm.Configuration.defaultConfiguration = config
        
        let realm = try! Realm()
        print(realm.objects(PomodoTask.self).first)
}
```

**Comment by Softminilab** [comment]
<img width="1013" alt="error" src="https://cloud.githubusercontent.com/assets/717235/23998358/d3d41d44-0a8f-11e7-8324-9ed7698c874f.png">

**Comment by hsylife** [comment]
@karepbq,
Could you check out my latest commit?
I have pushed it 5 mins ago.
I hope that I have fixed the error although I haven't confirmed it on my apple watch yet.

It seems it was caused because I had forgotten to copy the received file into the modifiable directory.

I will make sure it looks fixed by myself as soon as my apple watch got available.

**Comment by Softminilab** [comment]
ok, I'm try.

**Comment by Softminilab** [comment]
okay,Perfect running. thank you very much.
